### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-booster#46]
Here is feedback on changes we should make to the docs before going live:

```[tasklist]
### Tasks
- [x] Can we split it into a few pages, i.e. frontpage, usage, configuration, how it works
- [x] In the intro chapter, add a section about our goals for this app (i.e. minmal interference), and who should use it
- [x] I'm missing "cache survices xp restart" feature
- [x] Create a chapter/page "Usage" add installation, license and mention configuration there (link to config chapter), but also add a section on adding it to your site, configuring "exclude paths", how to verify that it is working and how to clear cache
- [x] There is a "Dashboard" section, do we have a widget? If so there should be a screenshot
- [x] Add a "config" page, where all sections related to configuration are placed
- [x] Add a "how it works" page where we explain details related to request/response
- [x] Missing a section explaining the booster "cache header"
- [x] 304 and max age sections are not sub-items of request collapsing afaik?
```
