### ISSUE TITLE
Acceptance Testing

### ISSUE THREAD

**Issue by rymsha** [enonic/app-booster#50]
```[tasklist]
### Tasks
- [x] Test exclusion
- [x] Test  install app cache clearing
- [x] Test publish-based cache clearing
- [x] Test schedule-based cache clearing
- [ ] https://github.com/enonic/app-booster/issues/49
- [x] Test purging (set small cache size?)
- [x] Test manual cache clearing
```

**Comment by sigdestad** [comment]
Here is the load graph, showing high load when rendering without booster, and just a small hump 13:10  rendering with. Same amount of requests
![Uploading Screenshot 2024-04-13 at 19.55.04.png…]()
